version: "3"

services:
  wallet-mysql:
      image: mysql:latest
      container_name: mysql
      restart: always
      ports:
         - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wallet
      networks:
        - common-network

  microservice-config-server:
          build:
              dockerfile: ./Dockerfile
              context: ./config-server
          image: abraaoribeiro/microservice-config-server
          container_name: microservice-config-server
          restart: always
          ports:
              - "8888:8888"
          networks:
              - common-network

  microservice-eureka-server:
      build:
         dockerfile: ./Dockerfile
         context: ./eureka-server
      image: abraaoribeiro/microservice-eureka-server
      container_name: microservice-eureka-server
      restart: always
      hostname: eureka-server
      ports:
           - "8761:8761"
      networks:
           - common-network

  microservice-gateway:
        build:
           dockerfile: ./Dockerfile
           context: ./gateway
        image: abraaoribeiro/microservice-gateway
        container_name: microservice-gateway
        restart: always
        depends_on:
             - microservice-eureka-server
        links:
            - microservice-eureka-server
        ports:
             - "5555:5555"
        environment:
                eureka.client.serviceUrl.defaultZone: http://microservice-eureka-server:8761/eureka/
        networks:
            - common-network

  microservice-client-api:
      build:
         dockerfile: ./Dockerfile
         context: ./client-api
      image: abraaoribeiro/microservice-client-api
      container_name: microservice-client-api
      depends_on:
          - wallet-mysql
          - microservice-account-api
          - microservice-config-server
      ports:
          - "8084:8084"
      environment:
               eureka.client.serviceUrl.defaultZone: http://microservice-eureka-server:8761/eureka/
               spring.cloud.config.uri: http://microservice-config-server:8888
      networks:
          - common-network

  microservice-account-api:
      build:
         dockerfile: ./Dockerfile
         context: ./account-api
      image: abraaoribeiro/microservice-account-api
      container_name: microservice-account-api
      depends_on:
           - wallet-mysql
           - microservice-config-server
           - microservice-eureka-server
      links:
           - wallet-mysql:wallet-mysql
           - microservice-eureka-server
      ports:
           - "8081:8081"
      environment:
              eureka.client.serviceUrl.defaultZone: http://microservice-eureka-server:8761/eureka/
              spring.cloud.config.uri: http://microservice-config-server:8888
      networks:
           - common-network

  microservice-payment-api:
        build:
           dockerfile: ./Dockerfile
           context: ./payment-api
        image: abraaoribeiro/microservice-payment-api
        container_name: microservice-payment-api
        depends_on:
            - wallet-mysql
            - microservice-client-api
            - microservice-account-api
            - microservice-eureka-server
        ports:
            - "8086:8086"
        environment:
                eureka.client.serviceUrl.defaultZone: http://microservice-eureka-server:8761/eureka/
                spring.cloud.config.uri: http://microservice-config-server:8888
        networks:
            - common-network

networks:
    common-network :
        driver: bridge
