version: "3"

services:
  wallet-service-db:
      image: mysql:8.0
      container_name: wallet-service-db
      restart: always
      ports:
         - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wallet