server:
    port: 8082

spring:
    datasource:
        initialization-mode: always
        continue-on-error: true
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: 123456

eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka

keycloak:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8085/auth}
    realm: ${KEYCLOAK_REALM:wallet-service}
    resource: ${KEYCLOAK_CLIENT_ID:account-api}
    credentials:
        secret: ${KEYCLOAK_SECRET:c80b7aa3-4c0c-48c5-8846-34e326bd15b}
    ssl-required: external
    use-resource-role-mappings: true
    bearer-only: true