server:
    port: 8082

spring:
    datasource:
        initialization-mode: always
        continue-on-error: true
    rabbitmq:
      host: rabbitmq
      port: 5672
      username: admin
      password: 123456

eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka
