server:
    port: 8086

spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: 123456

    listener:
          simple:
            retry:
              enabled: true
              initial-interval: 1000
              max-attempts: 2
              max-interval: 10000
              multiplier: 2.0
              stateless: true

eureka:
    client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka
