server:
   port: 8888

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          label: master
          uri: https://github.com/abraaoribeiro/microservice-repo
          search-paths: client,account,payment